import 'dart:convert';

import 'package:http/http.dart' as http;

import 'image_search_service.dart';

/// fal.ai Flux 2 — generates a dish image when no stock photo is found.
///
/// Used as the last-resort sync provider so every dish has at least one
/// image before the user sees the result. Cost: ~$0.008/image.
///
/// See: https://fal.ai/models/fal-ai/flux-2
class FalAiImageService extends ImageSearchService {
  @override
  bool get producesEphemeralUrls => true;

  static const _endpoint = 'https://fal.run/fal-ai/flux-2/text-to-image';

  final String _apiKey;
  final http.Client _httpClient;

  FalAiImageService({
    required String apiKey,
    http.Client? httpClient,
  })  : _apiKey = apiKey,
        _httpClient = httpClient ?? http.Client();

  @override
  String get providerId => 'fal_ai';

  @override
  Future<List<DishImageResult>> search(String dishName, {int limit = 1}) async {
    final body = jsonEncode({
      'prompt': 'A professional, appetizing food photograph of $dishName, '
          'restaurant menu style, soft natural lighting, shallow depth of field',
      'image_size': 'square_hd',
      'num_images': limit,
    });

    final response = await _httpClient.post(
      Uri.parse(_endpoint),
      headers: {
        'Authorization': 'Key $_apiKey',
        'Content-Type': 'application/json',
      },
      body: body,
    );

    if (response.statusCode == 429) {
      throw ImageSearchRateLimited(providerId);
    }
    if (response.statusCode != 200) {
      throw Exception('fal.ai error ${response.statusCode}: ${response.body}');
    }

    final decoded = jsonDecode(response.body) as Map<String, dynamic>;
    final images = (decoded['images'] as List<dynamic>?) ?? [];

    return images.map<DishImageResult>((i) {
      final img = i as Map<String, dynamic>;
      return DishImageResult(
        source: providerId,
        imageUrl: img['url'] as String? ?? '',
        attribution: 'Generated by fal.ai Flux',
      );
    }).where((r) => r.imageUrl.isNotEmpty).toList();
  }
}
